### PR TITLE
Make "handleStyle" optional and "top" and "left" configurable

### PR DESCRIPTION
**Pull request by Franziskus1988**
handleStyle should be declared as optional, since it is optional on code.

"top" and "left" should be configurable, because one might want to use e.g. top: 0% and height: 100% so handle covers the complete height.

### CODE REVIEW

**Comment by titovmx** [comment]
@Franziskus1988 thank you for the contribution! It definitely makes sense and looks fine for me

**Comment by Franziskus1988** [comment]
@titovmx  Do you plan to update the version number in the package.json? I forget to do this in the pull request.

**Comment by titovmx** [comment]
@Franziskus1988 I've updated the version number to 1.0.1 and published it to npm

**Comment by Franziskus1988** [comment]
Really cool. Thanks a lot.

**Pull request merged**
